apiVersion: v1
kind: ReplicationController
metadata:
  name: calico-policy-agent
  namespace: kube-system
  labels:
    version: v1
    projectcalico.org/app: "policy-agent"
spec:
  replicas: 1
  selector:
    version: v1
    projectcalico.org/app: "policy-agent"
  template:
    metadata:
      labels:
        version: v1
        projectcalico.org/app: "policy-agent"
    spec:
      containers:
      - image: alexhersh/calico-policy-agent
        env:
        - name: KUBE_API_ROOT
          value: "http://<KUBERNETES_MASTER>:8080/api/v1/"
        - name: ETCD_AUTHORITY
          value: "<KUBERNETES_MASTER>:4001"
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        name: policyagent
